// <copyright file="PostOperationcfasms_studenteducationhistoryUpdate.cs" company="">
// Copyright (c) 2023 All Rights Reserved
// </copyright>
// <author></author>
// <date>8/22/2023 8:49:54 PM</date>
// <summary>Implements the PostOperationcfasms_studenteducationhistoryUpdate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;

namespace StudentManagementSystem.cfasms
{

    /// <summary>
    /// PostOperationcfasms_studenteducationhistoryUpdate Plugin.
    /// Fires when the following attributes are updated:
    /// cfasms_institution,cfasms_iscurrentlyinprogress
    /// </summary>    
    public class PostOperationcfasms_studenteducationhistoryUpdate: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostOperationcfasms_studenteducationhistoryUpdate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information.</param>
        public PostOperationcfasms_studenteducationhistoryUpdate(string unsecure, string secure)
            : base(typeof(PostOperationcfasms_studenteducationhistoryUpdate))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// </remarks>
        protected override void ExecuteCdsPlugin(ILocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException(nameof(localContext));
            }           
            // Obtain the tracing service
            ITracingService tracingService = localContext.TracingService;

            try
            { 
                // Obtain the execution context from the service provider.  
                IPluginExecutionContext context = (IPluginExecutionContext)localContext.PluginExecutionContext;

                // Obtain the organization service reference for web service calls.  
                IOrganizationService currentUserService = localContext.CurrentUserService;

                // Implement your custom Plug-in business logic.
                if (context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)
                {
                    tracingService.Trace(PluginClassName + " contains Target and is Entity.");
                    Entity studenteducationhistory = (Entity)context.InputParameters["Target"];

                    // verify that target entity represents student education history table
                    if (studenteducationhistory.LogicalName != "cfasms_studenteducationhistory")
                        return;

                    Entity postImage = (Entity)context.PostEntityImages["PostImage"];
                   
                    // only do the work if currently enrolled
                    bool isCurrentlyInProgress = GetAttributeValue<bool>(studenteducationhistory, postImage, "cfasms_iscurrentlyinprogress");
                    // only change the college student ID if instituion has changed.
                    bool isDifferentInstitution = studenteducationhistory.Attributes.ContainsKey("cfasms_institution");
                    // if there isn't an assigned college student ID assign it regardless
                    bool isIdEmpty = string.IsNullOrEmpty(postImage.GetAttributeValue<string>("cfasms_name"));
                    // must be in progress... case 1: institution or id is empty... case 2: institution changed but ID not empty
                    if (isCurrentlyInProgress && ((isDifferentInstitution || isIdEmpty) || (!isDifferentInstitution && !isIdEmpty)))
                    {
                        Guid studenteducationhistoryId = (Guid)studenteducationhistory["cfasms_studenteducationhistoryid"];
                        EntityReference universityReference = GetAttributeValue<EntityReference>(studenteducationhistory, postImage, "cfasms_institution");
                        EntityReference studentReference = postImage.GetAttributeValue<EntityReference>("cfasms_student");

                        // get the last entered student-college id for the assigned institution with query expression
                        var query = new QueryExpression("cfasms_studenteducationhistory")
                        {
                            TopCount = 1,
                            ColumnSet = new ColumnSet("cfasms_name", "cfasms_institution"),
                            Criteria = new FilterExpression
                            {
                                FilterOperator = LogicalOperator.And,
                                Conditions =
                                {
                                    new ConditionExpression("cfasms_institution", ConditionOperator.Equal, universityReference.Id),
                                    new ConditionExpression("cfasms_name", ConditionOperator.NotNull),
                                    new ConditionExpression("cfasms_name", ConditionOperator.NotEqual, ""),
                                    new ConditionExpression("cfasms_student", ConditionOperator.NotEqual, studentReference.Id)
                                }
                            },
                            Orders =
                        {
                            new OrderExpression("createdon", OrderType.Descending)
                        }
                        };
                        // Query the last entered college ID. studenteducationhistoryId doesn't need changed because its available in update
                        EntityCollection result = currentUserService.RetrieveMultiple(query);

                        // Updated entity values
                        Entity updateEntity = new Entity("cfasms_studenteducationhistory", studenteducationhistoryId);
                        if (result.Entities.Count > 0)
                        {
                            // assign new id based on last entered id for the given instituion
                            string lastEnteredId = result.Entities[0].GetAttributeValue<string>("cfasms_name");
                            updateEntity["cfasms_name"] = util.createUpdatedId(lastEnteredId);
                            currentUserService.Update(updateEntity);

                        }
                        else
                        {
                            Entity universityEntity = currentUserService.Retrieve("cfasms_institutions", universityReference.Id, new ColumnSet("cfasms_name"));
                            string universityName = universityEntity.GetAttributeValue<string>("cfasms_name");

                            // if an id hasn't been created yet create one
                            updateEntity["cfasms_name"] = util.createNewId(universityName);
                            currentUserService.Update(updateEntity);
                        }

                    }
                }


            }

            // Only throw an InvalidPluginExecutionException. Please Refer https://go.microsoft.com/fwlink/?linkid=2153829.
            catch (Exception ex)
            {
                tracingService?.Trace("An error occurred executing Plugin StudentManagementSystem.cfasms.PostOperationcfasms_studenteducationhistoryUpdate : {0}", ex.ToString());
                throw new InvalidPluginExecutionException("An error occurred executing Plugin StudentManagementSystem.cfasms.PostOperationcfasms_studenteducationhistoryUpdate .", ex);
            }	
        }

        private static T GetAttributeValue<T>(Entity target, Entity postImage, string attributeName)
        {
            return target.Attributes.ContainsKey(attributeName)
                ? target.GetAttributeValue<T>(attributeName)
                : postImage.GetAttributeValue<T>(attributeName);
        }
    }
}
